spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: "classpath:/static/,file:./uploads/"
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/gallerydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: eu-central-1
